# (C) A.Voß – codebasedlearning.dev – Study Maths and Computer Science (AMI) with us @ FH Aachen – https://ami.codebasedlearning.dev

# Codebook configuration

# Where the short ref forms look when they carry no path of their own
glossary.path = ./docs/glossary.md, ./docs/answers.md
